import type { Metadata } from "next"
import { inter, instrumentSerif } from "@/app/fonts"
import "./globals.css"
import Navbar from "@/components/Navbar"
import { ThemeProvider } from "@/components/ThemeProvider"
import { TooltipProvider } from "@/components/ui/tooltip"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      className={`${instrumentSerif.variable} ${inter.variable}  antialiased`}
      suppressHydrationWarning
    >
      <body className='min-h-full flex flex-col'>
         <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
          <TooltipProvider>
            <Navbar />
            {children}
          </TooltipProvider>
          </ThemeProvider>
        </body>
    </html>
  )
}
