import type { Metadata } from "next";
import { Inter, Instrument_Serif } from "next/font/google";
import "./globals.css";

export const inter  = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const instrumentSerif = Instrument_Serif({
    weight: "400",
    subsets: ["latin"],
    variable: "--font-instrument-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
                className={`${instrumentSerif.variable} ${inter.variable}  antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
